### ISSUE TITLE
Add/confirm analytics are on the site

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#100]
Here’s the script URL  that the developers will need to add to the head tag of the page:
 
<script src="https://assets.adobedtm.com/a7d65461e54e/9ee19a80de10/launch-882c01867cbb.min.js" async></script>

**Comment by pfulton** [comment]
This should be fairly straight-forward.

@davidnuescheler - from a performance standpoint, do I need to do anything special here, or can I just add the `script` tag to the `head`?

**Comment by pfulton** [comment]
I inadvertently closed this the other day! Re-opened & issued #155 against it.
