### ISSUE TITLE
Increase H1 size on homepage carousel

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#104]
Increase H1 size on homepage carousel should have more presence than the homepage cards below, per Shawn 2/24 meeting.

Work with Jos to determine accurate sizing

<img width="1552" alt="Screen Shot 2022-02-24 at 6 37 14 PM" src="https://user-images.githubusercontent.com/100241986/155643167-3115dc7c-d1bb-4d2c-8a97-0d5338d53d09.png">

**Comment by pfulton** [comment]
@sharrocksb do we remember how much he said to increase it by? I vaguely remember a mention of "bigger than the story card titles below". Might need to ask Jos for guidance.

**Comment by sharrocksb** [comment]
@pfulton - I updated the comment above. Your memory was accurate - the ask was for the H1 header carousel to be slightly larger than the story card H1s. I'd recommend reaching out to Jos for more detailed direction.

**Comment by pfulton** [comment]
closed by #152
