### ISSUE TITLE
Adjust title leading of headlines in the people section on homepage

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#106]
Headline leading in the People section on the homepage should match other title leading.

<img width="1221" alt="Screen Shot 2022-02-24 at 6 44 41 PM" src="https://user-images.githubusercontent.com/100241986/155643980-833d5233-dbb7-4225-a9c1-1e9e0c84e9bb.png">

**Comment by sharrocksb** [comment]
@pfulton - I opened a new issue ( #163  ) to address the line height and font size relationships. feel free to close this one, if helpful. I hope it's not too confusing.

**Comment by pfulton** [comment]
Closed via #162
