### ISSUE TITLE
Animate accordion carrot to indicate when section is open/closed

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#108]
Animate the accordion '>' to indicate when a section is open or closed. '^' should point to the right when closed and shift 90 degree down when open.
<img width="391" alt="Screen Shot 2022-02-24 at 6 55 52 PM" src="https://user-images.githubusercontent.com/100241986/155645193-04786a8c-926f-466f-87eb-3b2e5e694428.png">

**Comment by pfulton** [comment]
Closed by #180
