### ISSUE TITLE
'Prototyping and Engineering' Accordion overlaps blocks when screen size reduced

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#109]
The 'Prototyping and Engineering' accordion still overlaps color block when screensize reduced in Chrome. 
<img width="1440" alt="Screen Shot 2022-02-24 at 7 02 02 PM" src="https://user-images.githubusercontent.com/100241986/155645875-6f7292de-661d-48ee-995c-b385b03e514f.png">

**Comment by pfulton** [comment]
@cjgammon I know you did some work in #81 to address this, but it looks like it's still happening occasionally. I haven't taken a deep look at this, but I'm open to whatever solution(s) would fix it and future-proof it.

**Comment by pfulton** [comment]
Closed by #180
