### ISSUE TITLE
Adjust padding on Team page between 'Cloud' block and 'Think Differently' block

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#111]
Match to the XD design file

<img width="1230" alt="Screen Shot 2022-02-24 at 7 06 44 PM" src="https://user-images.githubusercontent.com/100241986/155646154-917f55f6-f8ad-423b-beab-6f3811f5289c.png">

Design file:
<img width="227" alt="Screen Shot 2022-02-24 at 7 08 54 PM" src="https://user-images.githubusercontent.com/100241986/155646355-5701f265-815b-4549-85cf-03c1251bb717.png">

**Comment by pfulton** [comment]
Closed via work done in #140
