### ISSUE TITLE
On Stories page, adjust headline size to avoid breaking words when resizing

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#112]
Resize headline text to avoid breaking headline words. Option to remove subtitle and byline to keep the image more prominent than text size.

If resizing text, everything should be proportionally adjusted. Work with Jos to ensure design alignment.

Text block should ideally be no more than 40% of the image height.

<img width="1076" alt="Screen Shot 2022-02-24 at 7 10 10 PM" src="https://user-images.githubusercontent.com/100241986/155646699-364ac222-1ebd-43f1-80ab-3c70ac425b53.png">

**Comment by pfulton** [comment]
May have been addressed via #135, but let's double-check with Jos.

**Comment by sharrocksb** [comment]
Thanks, Patrick! The site looks AMAZING! I think this does solve the line break issue. I didn't see any issues.

My only concern is how long the text block gets on narrower views. I believe Andrea and Shawn will want to remove dek and byline from narrower screen views so the image remains more prominent. I can add a separate issue specific to this ask.

**Comment by pfulton** [comment]
Closed via #178
