### ISSUE TITLE
Article heading line heigh spacing to be adjusted

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#114]
Adjust line height spacing by approx 5% and apply universally to headlines.
<img width="731" alt="Screen Shot 2022-02-24 at 7 18 50 PM" src="https://user-images.githubusercontent.com/100241986/155647444-161086c3-e16d-49be-9d4f-3891420713b0.png">

**Comment by pfulton** [comment]
This is a refactor opportunity. We can/should use a custom property for this, and [one is already established](https://github.com/adobe/design-website/blob/26cc5c3ff29eae3f577c159ee7147e03a9b4a353/styles/styles.css#L83). This should be adjusted site-wide and a successful refactor should include using a common selector.
