### ISSUE TITLE
Resolve Andreas Küfer author pull

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#115]
Andreas's byline doesn't appear on the page. I'm assuming it's because the author page isn't recognized for the special character in the title. 

article: https://main--design-website--adobe.hlx3.page/stories/leading-design/its-an-interview-not-an-interrogation

<img width="664" alt="Screen Shot 2022-02-24 at 7 20 29 PM" src="https://user-images.githubusercontent.com/100241986/155647669-75a09f9e-d856-4845-809e-1dc60e9c8a09.png">

**Comment by pfulton** [comment]
The Helix team might be interested in hearing about this one. I'm not sure if this is a known issue, @davidnuescheler .

**Comment by pfulton** [comment]
[Here's where I'm grabbing and displaying the author data](https://github.com/adobe/design-website/blob/26cc5c3ff29eae3f577c159ee7147e03a9b4a353/blocks/lede/lede.js#L67-L88).

**Comment by sharrocksb** [comment]
@pfulton - Can I have you pull Andreas's name from the file and not the metadata here? If so, this can be resolved by removing the special character from the file name/metadata, but keeping it in the page header.

<img width="974" alt="Screen Shot 2022-03-03 at 9 28 26 PM" src="https://user-images.githubusercontent.com/100241986/156705251-2b69d38a-0160-45ab-b0c7-9ac556ecdb74.png">
.
