### ISSUE TITLE
Adjust sizing of pull quotes

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#118]
Adjust pull quote sizing in partnership with Jos to help adjust and align with different header styles.

Give more space on top and bottom to align with the design file.

See also #95 

Article example: https://main--design-website--adobe.hlx3.page/stories/design-for-scale/orchestrating-commerce-experiences 

<img width="1056" alt="Screen Shot 2022-02-24 at 10 32 47 PM" src="https://user-images.githubusercontent.com/100241986/155666298-04efa3f3-ba8f-4a4d-b861-8b223be920e0.png">

**Comment by sharrocksb** [comment]
@pfulton  - FYI - the style is only applied to annotated pull quotes, but it should be applied to blocks equally.

You can find an example here: https://main--design-website--adobe.hlx3.page/stories/unpublished/example-article

<img width="1285" alt="Screen Shot 2022-03-03 at 10 03 04 PM" src="https://user-images.githubusercontent.com/100241986/156708664-f053e725-1c32-42d0-9e28-d5974af92dae.png">

**Comment by sharrocksb** [comment]
FYI, @pfulton - it looks like even in this new chore, the regular pull quotes still aren't being styled properly. Let me know if it would help to talk through this! 

<img width="1459" alt="Screen Shot 2022-03-08 at 9 39 14 AM" src="https://user-images.githubusercontent.com/100241986/157294781-e44c0f61-5dc2-4aa7-93d4-60d6e65680af.png">

**Comment by pfulton** [comment]
@sharrocksb great catch. I've fixed it and it'll be in #178
