### ISSUE TITLE
Swap toolkit images

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#119]
swap toolkit images with high-res options

**Comment by pfulton** [comment]
@sharrocksb just a reminder that the Inclusive Design image should have a non-transparent background. I think the design suggests a white background.

**current image on site**
<img width="1730" alt="Screen Shot 2022-02-25 at 10 05 31 AM" src="https://user-images.githubusercontent.com/360251/155738220-ff334b38-2dfb-4af8-adc9-f61408fd8717.png">

**Comment by sharrocksb** [comment]
Yes! Thank you, @pfulton! I'll go ahead and swap and adjust background if needed once I have files from Matt.

**Comment by sharrocksb** [comment]
Images have been swapped with help from Jos with color selection
