### ISSUE TITLE
'Apply Now' CTA on jobs posting is low on Chrome/laptop

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#121]
Apply Now button on the job posting page is low and almost disappears when viewed on Chrome on a laptop. Either reduce the headline/job title font size or move the CTA up higher
<img width="1360" alt="Screen Shot 2022-02-24 at 10 46 54 PM" src="https://user-images.githubusercontent.com/100241986/155668158-45aa43a9-0c5f-4e75-aa6c-299b1bace551.png">

**Comment by pfulton** [comment]
This also breaks at various viewport sizes.

<img width="160" alt="Screen Shot 2022-02-24 at 12 03 40 PM" src="https://user-images.githubusercontent.com/360251/155735999-31b70802-b68c-489f-b7dc-6309572a7682.png">
