### ISSUE TITLE
Carousel H1, H2, and byline too high

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#150]
The text block for the Carousel block is still too high on laptop when viewed in Chrome. 

**From the site:**
<img width="1552" alt="Screen Shot 2022-03-01 at 8 27 17 PM" src="https://user-images.githubusercontent.com/100241986/156295017-b2aa930a-20c0-4dcb-b88f-5a7ff0781aa5.png">

**From the design file:**
<img width="457" alt="Screen Shot 2022-03-01 at 8 28 18 PM" src="https://user-images.githubusercontent.com/100241986/156295080-8b94e73d-fb41-4894-a361-c7ad25f0c364.png">

**Comment by pfulton** [comment]
Closed by #152
