### ISSUE TITLE
Homepage carousel text falls behind cards on narrow screens

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#151]
When a user browses the homepage with a narrow viewport, the carousel text falls below the image and sometimes ends up behind the homepage cards.

Screenshot:
<img width="990" alt="Screen Shot 2022-03-01 at 8 30 23 PM" src="https://user-images.githubusercontent.com/100241986/156295258-af3fae9d-0770-4c87-9228-52cda6aac0e4.png">

**Comment by pfulton** [comment]
Closed by #152
