### ISSUE TITLE
Remove 'full-time' from homepage job descriptions

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#159]
Since the 'underline' on the serifed font looks weird with the parentheses, we're hoping to remove the 'full-time' from job postings on the homepage.

<img width="1689" alt="Screen Shot 2022-03-03 at 10 27 45 AM" src="https://user-images.githubusercontent.com/100241986/156636632-f83e3344-54a1-4854-a82a-7cb727007b49.png">

**Comment by pfulton** [comment]
Closed via #172
