### ISSUE TITLE
.live stories page is showing the stats block at the top of the page

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#164]
Not sure who can resolve this, but I wanted to flag that the stats block is appearing at the top of the Stories landing page.
<img width="1302" alt="Screen Shot 2022-03-03 at 9 34 29 PM" src="https://user-images.githubusercontent.com/100241986/156705788-d81466c6-6848-40b6-b63c-4d72d32de744.png">

**Comment by pfulton** [comment]
@sharrocksb I'm not sure why it was doing that, but I fixed it just now. For some reason, I had to go to that URL and use the bookmarklet to republish _while at that URL (not from within Word)_.
