### ISSUE TITLE
Target pull quote to remove top margin slightly

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#166]
Around 7:30 in the meeting recording. https://adobe-my.sharepoint.com/personal/pfulton_adobe_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpfulton%5Fadobe%5Fcom%2FDocuments%2FRecordings%2FMeeting%2D20220303%5F203550%2DMeeting%20Recording%2Emp4&parent=%2Fpersonal%2Fpfulton%5Fadobe%5Fcom%2FDocuments%2FRecordings

I think you might have resolved this, Patrick, but it wasn't on the list, so I wanted to capture here.

I'm not sure how much you adjusted the padding, but the goal was to have it balance between top and bottom while accommodating the paragraph break spacing that exists. . I couldn't capture the exact adjustment you made live, but I'm hoping the recording will help.

**Comment by pfulton** [comment]
Yep, got this one! The code change is [here](https://github.com/adobe/design-website/pull/162/files#diff-1585259f8737e6a5690a7655fe57bf333feb4ef12ce828aa5fd2eea0330848f5R23).
