### ISSUE TITLE
Landing page  H1 - settle on one layout for all pages

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#170]
It sounded like Jos wanted to move forward with following the Team page layout for the other landing pages - Stories, Toolkit, and Jobs.

This means that the font size, line height, and placement on the page should match across landing pages (plus the Inclusive Design page).

The relationship to the body copy should also be the same.

this was discussed at the 38min mark in the [recording](https://adobe-my.sharepoint.com/personal/pfulton_adobe_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpfulton%5Fadobe%5Fcom%2FDocuments%2FRecordings%2FMeeting%2D20220303%5F203550%2DMeeting%20Recording%2Emp4&parent=%2Fpersonal%2Fpfulton%5Fadobe%5Fcom%2FDocuments%2FRecordings)

<img width="699" alt="Screen Shot 2022-03-03 at 11 04 41 PM" src="https://user-images.githubusercontent.com/100241986/156715775-1b359e45-4ace-457e-bd0a-4737c435921b.png">

**Comment by pfulton** [comment]
Closed via #178
