### ISSUE TITLE
Redirect showing on the .live site

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#188]
I just tested going to the Inclusive Design page on .live and I ran into the redirect card we're supposed to see on stage.
<img width="1552" alt="Screen Shot 2022-03-10 at 4 27 34 PM" src="https://user-images.githubusercontent.com/100241986/157778340-7053ddcd-1050-4365-9a36-0f3bde20f631.png">

**Comment by pfulton** [comment]
@davidnuescheler - is this the expected behavior on `.live`?

**Comment by sharrocksb** [comment]
This was resolved this morning and it's looking beautiful!!
