### ISSUE TITLE
On homepage, apply article dek style to profiles job title/subhead to article dek

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#190]
Apply the article subtitle style (i.e. Marisa Bazan on paper, scissors, and glue) to the job title in the people/profile block. 

FYI - Jos and Shawn may also want to adjust the font sizes of this block, but they've asked for first see the dek/subhead style applied to the job title. 

<img width="529" alt="Screen Shot 2022-03-11 at 9 21 10 AM" src="https://user-images.githubusercontent.com/100241986/157916095-3b5d3626-73db-4a42-87f7-8315332f8922.png">

**Comment by pfulton** [comment]
@sharrocksb - I just put a PR in for this. Check out the URL here and let me know if that works for everyone: https://github.com/adobe/design-website/pull/191
