### ISSUE TITLE
Reduce pull quote padding by 30% on top and bottom

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#219]
Top + bottom margin - pull quote: reduce by 30%

On desktop - I'm having trouble giving clear numbers because of the coding, but let's do 65px total on top and bottom (so adjust the top padding down to 41px; plus the paragraph padding 24px).  For the bottom margin, aim for 65px total on 
<img width="1360" alt="Screen Shot 2022-03-15 at 11 29 25 PM" src="https://user-images.githubusercontent.com/100241986/158530291-f987cf0b-ee1c-4803-b594-950f5ae0566b.png">

On ipad and mobile, the top margin should increase to match the bottom margin.
<img width="1360" alt="Screen Shot 2022-03-15 at 11 33 04 PM" src="https://user-images.githubusercontent.com/100241986/158530641-3c3cecbe-fadf-44cd-869f-7a3e8825a479.png">
<img width="1360" alt="Screen Shot 2022-03-15 at 11 32 31 PM" src="https://user-images.githubusercontent.com/100241986/158530651-22adbef0-dc08-4340-959a-4ea8f765297e.png">

**Comment by sharrocksb** [comment]
@pfulton - giving this a nudge instead of adding a new issue. Let me know if you have any questions. Lots of math in this one. 🤦🏻‍♀️

**Comment by pfulton** [comment]
Just adjusted this via our conversation in Slack! Will be closed via #222
