### ISSUE TITLE
Profile image credit breaking around 1200px screen width

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#241]
The profile page layout breaks around the 1200px screen width when viewed on Chrome/desktop.

<img width="1455" alt="Screen Shot 2022-03-18 at 2 08 16 PM" src="https://user-images.githubusercontent.com/100241986/159083367-502ed0d8-e4d1-4e19-bdd3-2977f88f9508.png">

**Comment by pfulton** [comment]
Closed via #134
