### ISSUE TITLE
Adjust padding for text on the accordion

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#248]
Adjust padding for the text on the accordion. I had a tricky time measure between the horizontal line and the body copy, but I figured it was about 34px between the two.  

**Updated padding/margins:**
1. Between the top of the card and the header text bump up 58px, similar to the image padding on the Article pages
2. Between the horizontal line and the body copy, there is about 49px.
3. Below the object should be 49px

<img width="1638" alt="Screen Shot 2022-03-18 at 4 44 59 PM" src="https://user-images.githubusercontent.com/100241986/159098850-610fe078-c993-460b-9f04-8130d5d8ff15.png">

**Comment by cjgammon** [comment]
@sharrocksb these values aren't in pixels in the design and need to be responsive for different sizes, @pfulton did the layout of these cards originally, I just added the interactivity.  @pfulton how did you translate these values to rems?
