### ISSUE TITLE
Add head and footer to the 404 page 

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#249]
Add header and footer to the 404 page. The footer doesn't need to be visible in the viewport, but it should be there to give navigation options. 

Per David: possibly needs the addition of an empty <header> and <footer> html in your 404.html but that should be it?

**Comment by sharrocksb** [comment]
@pfulton - did you add the header and footer to the other pages? And do you know if it's an easy process?

**Comment by cjgammon** [comment]
@davidnuescheler is there a way to use blocks or existing components in the 404 page?  I'm curious because we have a lot of styles and components built for the header elsewhere and it would be ideal to reuse those here in the 404 page.
