### ISSUE TITLE
Sort stories page by date

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#261]
Sort the stories page by date; most recent and then move to the oldest stories.

**Comment by pfulton** [comment]
I think we've solved this one, correct @sharrocksb?

**Comment by sharrocksb** [comment]
Yes - the fix was adding {4} toward the end of the equation in the Column A on the helix-stories tab. 

{4} denoted which area of the spreadsheet to sort by and 'TRUE' denoted that it could be the column (as opposed to the row).

_Here is the full equation for reference:_
=SORT(FILTER(raw_index!A$2:A$453,LEFT(raw_index!A$2:A$453,9)="/stories/"),{4},1,TRUE)
