### ISSUE TITLE
Adjust mobile header styles for landing pages. 

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#263]
Adjust landing page headers to be inset by 2.5 rems - just on mobile.

Adjust All Stories title on iPad (fix to start of column 2)
<img width="551" alt="Screen Shot 2022-03-22 at 12 44 08 PM" src="https://user-images.githubusercontent.com/100241986/159563128-185a6d0a-3bb5-47e4-9186-313691d076ed.png">

**Comment by pfulton** [comment]
I noticed that we'd previously changed the story page title blocks to be inset by `1.875rem`, so I made all of the other page headers be the same. This will help when we move forward with adjusting the mobile grid/constrained size.

So, in summary: instead of using `2.5rem`, I used `1.875rem`.
