### ISSUE TITLE
Strange color gradient on mobile jobs pages

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#83]
Reviewing the job posts on the mobile (iPhone 8), there is a strange gradient that appears in the middle of the scroll.

And there is a line break in the job title that I'm hoping we can avoid (I know I'm working on a smaller screen, so if it's not possible. I doubt many people will be viewing on an iPhone 8)

https://user-images.githubusercontent.com/100241986/155266964-8adeedf6-c300-4186-8f8c-b5e16335df9b.MP4

**Comment by pfulton** [comment]
Will likely need to look at [this selector](https://github.com/adobe/design-website/blob/26cc5c3ff29eae3f577c159ee7147e03a9b4a353/styles/styles.css#L230-L232) and see if there's something else affecting this at small sizes.
