### ISSUE TITLE
Team accordion descriptions cut-off on full screen laptop

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#85]
When viewing the team page on full screen laptop, and a section is selected, it collapses as soon as scrolling up when viewed in Chrome on laptop, so the viewer can't read the full description. Can we make the font size slightly smaller, so it's readable? 

https://user-images.githubusercontent.com/100241986/155267979-cb976db0-f943-476b-9c29-28645a4b567a.mov

**Comment by pfulton** [comment]
Closed by #180
