### ISSUE TITLE
Reorder job posts on jobs page

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#86]
Can we reorder the job sections. Ideally, we'd lead with Experience Design, and Team Operations would be lower down the list, since we have job openings less often.

[Current Jobs Landing Page](https://main--design-website--adobe.hlx3.page/jobs/)

Patrick - please let me know how much time you anticipate this taking, since I may reprioritize it. 

<img width="1552" alt="Screen Shot 2022-02-22 at 9 52 40 PM" src="https://user-images.githubusercontent.com/100241986/155268181-77236812-368d-4751-beb6-7b2ac9909547.png">

**Comment by pfulton** [comment]
This is either a `1` or a `2` pointer. Probably closer to a `1`.

We'll need to do some kind of sorting on [the object that we create](https://github.com/adobe/design-website/blob/26cc5c3ff29eae3f577c159ee7147e03a9b4a353/blocks/opportunities/opportunities.js#L18) after we fetch all open jobs.

**Comment by sharrocksb** [comment]
Thanks, @pfulton! 

Here's the order we'd like jobs posting to appear:
**Left column:**
Experience Design

**Right column:**
Content Strategy
Design Ops Program Management
Prototyping and Engineering
Research and Strategy
Team Operations
Internships
