### ISSUE TITLE
Attached image credit to header image on profile headers

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#89]
The image credit should tie to the header image in the same proportions as the other article pages.

<img width="1552" alt="Screen Shot 2022-02-22 at 10 06 58 PM" src="https://user-images.githubusercontent.com/100241986/155269431-ca1eee25-0469-4d45-a962-b34e339e9307.png">

**Comment by pfulton** [comment]
This is likely related to [this CSS](https://github.com/adobe/design-website/blob/26cc5c3ff29eae3f577c159ee7147e03a9b4a353/blocks/lede/lede.css#L291-L298), or at least this selector across the other breakpoints. Keep an eye out for profile vs. non-profile pages.
