### ISSUE TITLE
Article headlines breaking at strange points

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#94]
Need to address headline wrapping of articles heds on mobile (tested on iPhone)

![Image from iOS (3)](https://user-images.githubusercontent.com/100241986/155435092-83dc1af6-228a-4bfd-b2a6-804d5ec08c1a.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/100241986/155435101-98aa5558-9add-4dad-b43c-dc51dc129838.png)

**Comment by pfulton** [comment]
Should be checked site-wide. May be related to [this CSS](https://github.com/adobe/design-website/blob/26cc5c3ff29eae3f577c159ee7147e03a9b4a353/styles/styles.css#L123).

**Comment by pfulton** [comment]
I've _sort of_ addressed this in #135 and things are looking a little better. I have some ideas for making things look better on small screens that I'd like to discuss.

**Comment by sharrocksb** [comment]
@pfulton - I'm guess the change you made here was making the side wider is that the case? If so, I added issue #161 to address additional margin adjustments with Jos.
