### ISSUE TITLE
Homepage carousel arrows need more room on either side + a hover state

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#98]
Let's give these a little more breathing room left and right (and they need a hover state) via Shawn in [Slack](https://adobedesign.slack.com/archives/C026SB22VFG/p1645736803533659) 
![image (3)](https://user-images.githubusercontent.com/100241986/155608054-dca56399-4472-47fd-95ad-4d4e9b3b8ca4.png)

**Comment by pfulton** [comment]
Closed by #152
